import os 
# os.system("python ./train.py eclipse_my_method_0.4")
# os.system("python ./train.py eclipse_my_method_0.3")
# os.system("python ./train.py eclipse_my_method_0.2")
# os.system("python ./train.py eclipse_my_method_0.1")
# os.system("python ./train.py eclipse_description_0.5")
# os.system("python ./train.py mozilla_my_method_0.5")
# os.system("python ./train.py mozilla_my_method_0.4")
# os.system("python ./train.py mozilla_my_method_0.3")
# os.system("python ./train.py mozilla_my_method_0.2")
# os.system("python ./train.py mozilla_my_method_0.1")
# os.system("python ./train.py mozilla_description_0.5")
#os.system("python ./train.py netbeans_my_method_0.5")
#os.system("python ./train.py netbeans_my_method_0.4")
os.system("python ./train.py netbeans_my_method_0.3")
os.system("python ./train.py netbeans_my_method_0.2")
os.system("python ./train.py netbeans_my_method_0.1")
os.system("python ./train.py netbeans_description_0.5")
# os.system("python ./train.py gcc_my_method_0.5")
# os.system("python ./train.py gcc_my_method_0.4")
# os.system("python ./train.py gcc_my_method_0.3")
# os.system("python ./train.py gcc_my_method_0.2")
# os.system("python ./train.py gcc_my_method_0.1")
# os.system("python ./train.py gcc_description_0.5")
